config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :status, only: [:index], controller: 'status'

  resources :projects do
    resources :tasks, only: [:new, :create, :destroy, :update, :edit]
  end


  resources :chat_rooms, only: [:show, :index, :new, :create] do
    resources :messages, only: [:create]
  end

  resources :settings, only: [:show]

  get '/home', to: 'pages#home', as: 'home'

  root to: 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # messanger
  mount ActionCable.server => "/cable"
end

app/views/shared/_footer.html.erb
<div class="footer hidden-xs hidden-sm">
  <div class="footer-links">
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    From Handy Harry with <i class="fa fa-heart"></i>
  </div>
</div>

app/views/shared/_inner_html.html.erb
<div class="row">
  <div class="col-xs-12">
    <div id="proj-<%="#{project.id}"%>' class="project">
      <a class="accordion-toggle collapsed"data-toggle="collapse" data-parent="#projectAccordion" href="#taskAccordion-<%="#{project.id}"%>" aria-expanded="true" aria-controls="taskAccordion">
        <i class="fa" aria-hidden="true"></i>
      </a>
      <div class="project-card">
        <div class="card-header">
          <img class="card-avatar" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
          <h3><%=project.address%></h3>
        </div>
        <div class="card-content">
          <div class="card-content-details">
            <div class="card-content-title">
              <i class="fa fa-wrench" aria-hidden="true"></i>
              <p class="project-title"> <%= project.title %></p>
            </div>
            <div class="card-content-location">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <p class="project-location"> <%= project.location %></p>
            </div>
          </div>
          <div class="card-content-contacts">
            <%= link_to "tel:#{current_user.handy ? project.client.phone : project.handy.phone}", class: "icon-link" do %>
            <i class="fa fa-phone fa-2x" aria-hidden="true"></i>
            <% end %>
            <%= simple_form_for ChatRoom.new, html: { class: "icon-z-index-form" } do |f| %>
            <% if current_user.handy %>
            <%= f.input :client_id, as: :hidden, input_html: { :value => project.client.id } %>
            <%= f.input :handy_id, :as => :hidden, :input_html => { :value => current_user.id } %>
            <% else %>
            <%= f.input :handy_id, :as => :hidden, :input_html => { :value => project.handy.id } %>
            <%= f.input :client_id, :as => :hidden, :input_html => { :value => current_user.id } %>
            <% end %>
            <%= button_tag("", type: "submit", class: "icon-link") do %>
            <i class="fa fa-comment" aria-hidden="true"></i>
            <% end %>
            <% end %>
            <%= link_to project.map_link, class: "icon-link", target: :_blank do %>
            <i class="fa fa-road fa-x2" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
        <%= link_to "", project_path(project), class: "tag-link" %>
      </div>
    </div>
  </div>
</div>
<div id="taskAccordion-<%="#{project.id}"%>" class="collapse" role="tabpanel">
  div class="row">
  <div class="todo-list">
    <% if project.tasks %>
    <% project.tasks.each do |task| %>
    <div class="todo">
      <%= simple_form_for [project, task], remote: true, html: { id: "form_#{task.id}" } do |f| %>
      <%= f.input :status, label: "#{task.description}", as: :boolean, label_html: {class: "todo__text"}, input_html: { id: "task-check-#{task.id}", class: "task-check todo__state", data: { task_id: task.id } } %>
      <% end %>
      <% if policy_scope(Task) || policy(Task).destroy? %>
      <div>
        <%= link_to project_task_path(id: task.id, project_id: project.id), method: :delete  do%>
        <i class="fa fa-trash" aria-hidden="true"></i>
        <% end %>
      </div>
      <% end %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon hidden-xs hidden-sm" style="background:<%= background %>; box-shadow:<%= shadow %>;">

  <!-- Left navigation -->


  <div class="navbar-search">
    <%= link_to home_path, class: "navbar-wagon-brand" do %>
       <%= image_tag "handyharry_logo.png" %>
    <% end %>
    <% if user_signed_in? %>
      <a href="#" id="search-icon"><i class="fa fa-search" aria-hidden="true"></i></a>
      <p class="search-bar"> Search</p>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <% if user_signed_in? %>

      <!-- Projects link -->

      <%= link_to projects_path, class: "navbar-wagon-link" do %>
        <i class="fa fa-wrench" aria-hidden="true"></i>
      <% end %>

      <!-- Chat Room link -->
      <%= link_to chat_rooms_path, class: "navbar-wagon-link" do %>
        <i class="fa fa-comment" aria-hidden="true"></i>
      <% end %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">


          <%= image_tag current_user.check_avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>


          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <% logout_path = destroy_user_session_path %>
              <%= link_to logout_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link for customers (when logged out) -->
      <%= link_to t(".sign_in", default: "Customers"), new_user_session_path, class: "btn btn-customers" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-right hidden-md hidden-lg">
    <% if current_user %>
      <%= link_to projects_path, class: "navbar-wagon-link" do %>
        <i class="fa fa-wrench" aria-hidden="true"></i>
      <% end %>
      <%= link_to chat_rooms_path, class: "navbar-wagon-link" do %>
        <i class="fa fa-comment" aria-hidden="true"></i>
      <% end %>
      <div class="navbar-wagon-xs-dropdown">
        <div class="dropdown">
          <%= image_tag current_user.check_avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <% logout_path = destroy_user_session_path %>
              <%= link_to logout_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>
        <!-- Login link for customers (when logged out) -->
        <%= link_to t(".sign_in", default: "Customers"), new_user_session_path, class: "btn btn-customers" %>
    <% end %>
  </div>

</div>


<% content_for(:after_js) do %>
  <script>
    $( "#search-icon" ).click(e => {
      e.preventDefault();
      $( ".search-bar" ).toggleClass( "active" );
      $(".search-bar").focus();
    });
  </script>
<% end %>

app/views/shared/_navigation.html.erb
<div class="navbar-wagon navigation-footer-position hidden-md hidden-lg">

  <!-- Dropdown list appearing on mobile only -->
<!--   <div class="navigation-middle"> -->
<% @url_path_check %>
<% url = request.path_info  %>
<% if url.include?('projects') %>
  <% @url_path_check = "pro" %>
<% elsif url.include?('chat_rooms') %>
  <% @url_path_check = "cha" %>
<% elsif url.include?('settings') %>
  <% @url_path_check = "set" %>
<% elsif url.include?('status') %>
  <% @url_path_check = "sta" %>
<% end %>

    <% if current_user %>
    <div class="navigation-icons-wrapper <%= "selected-nav" if @url_path_check == "sta"%>">
        <div class="navigation-icons text-center">
          <%= link_to status_index_path, class: "text-center" do %>
            <i class="fa fa-users no-padding-no-margin" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <div class="navigation-icons-wrapper <%= "selected-nav" if @url_path_check == "pro"%>">
        <div class="navigation-icons text-center">
          <%= link_to projects_path, class: "text-center" do %>
            <i class="fa fa-wrench no-padding-no-margin" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <div class="navigation-icons-wrapper <%= "selected-nav" if @url_path_check == "cha"%>">
        <div class="navigation-icons text-center">
          <%= link_to chat_rooms_path, class: "text-center" do %>
            <i class="fa fa-commenting<%= @url_path_check == "cha" ? "" : "-o" %> no-padding-no-margin" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <div class="navigation-icons-wrapper <%= "selected-nav" if @url_path_check == "set"%>">
        <div class="navigation-icons text-center">
          <%= link_to setting_path(current_user), class: "text-center" do %>
            <i class="fa fa-user<%= @url_path_check == "set" ? "" : "-o" %> no-padding-no-margin" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <!-- <div class="navigation-icons-wrapper <%#= "selected-nav" if @url_path_check == "use"%>">
        <div class="navigation-icons text-center">
            <div class="dropup">
              <i class="fa fa-user-o dropdown-toggle no-padding-no-margin" id="navbar-wagon-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li>
                  <%#= link_to "#" do %>
                    <i class="fa fa-user"></i> <%#= t(".profile", default: "Profile") %>
                  <%# end %>
                </li>
                <li>
                  <%# logout_path = destroy_user_session_path %>
                  <%#= link_to logout_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%#= t(".sign_out", default: "Log out") %>
                  <%# end %>
                </li>
              </ul>
            </div>
        </div>
      </div> -->
      <% else %>
        <!-- Login link for customers (when logged out) -->
        <%= link_to t(".sign_in", default: "Customers"), new_user_session_path, class: "btn btn-customers" %>
    <% end %>
  <!-- </div> -->
</div>

app/views/shared/_search_bar.html.erb
<%= form_tag(projects_path, method: :get, class:"form-for-search") do %>
  <%= text_field_tag :query, nil, class: 'form-control search-input', placeholder: "Search", id: "search_content" %>
  <%= submit_tag 'Search', :style => "display: none;" %>
<% end %>