config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :status, only: [:index], controller: 'status'

  resources :projects do
    resources :tasks, only: [:new, :create, :destroy, :update, :edit]
  end


  resources :chat_rooms, only: [:show, :index, :new, :create] do
    resources :messages, only: [:create]
  end

  resources :settings, only: [:show]

  get '/home', to: 'pages#home', as: 'home'

  root to: 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # messanger
  mount ActionCable.server => "/cable"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- mobile stuff -->
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'/>

    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- Facebook optimization -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta property="fb:app_id" content="132880950722117" />

    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:800|Roboto+Condensed" rel="stylesheet">
    </head>
  </head>
  <body>
<!-- jquery auto complete  -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<!-- jquery auto complete  -->
  <% if current_page?(home_path) %>
    <%= render 'shared/navbar', background: "transparent", shadow: "none" %>
  <% else %>
    <%= render 'shared/navbar', background: "#83DACE", shadow: "0 1px 5px 0 rgba(0,0,0,0.07),0 1px 0 0 rgba(0,0,0,0.03)" %>
  <% end %>

  <!-- mobile title -->
  <% if current_user %>
  <div class="placeholder"></div>
  <% if current_page?(projects_path) || current_page?(root_path) %>
    <h2 id="head-title" class="fixed-objects">Projects</h2>
  <% elsif current_page?(chat_rooms_path) %>
  <div class="chat-head fixed-objects">
    <h2 id="head-title" class="chats-header-icon">Chats</h2><%= link_to new_chat_room_path do %><i class="fa fa-pencil-square-o add-message-icon" aria-hidden="true"></i><% end %></div>
  <% elsif current_page?(status_index_path) %>
    <h2 id="head-title" class="fixed-objects">Status</h2>
  <% elsif current_page?(setting_path(current_user)) %>
    <h2 id="head-title" class="fixed-objects">Profile</h2>
  <% end %>

  <!-- search bar in chats and projects -->
    <% if current_page?(projects_path) || current_page?(chat_rooms_path) || current_page?(root_path) %>
      <%= render 'shared/search_bar'%>
    <% end %>
  <% end %>


    <div class="main">
      <%= yield %>
    </div>
  <!-- optimized navigation on mobile -->
    <%= render 'shared/navigation' %>
  <!-- optimized navigation on mobile -->
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- mobile stuff -->
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'/>
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">

        <!-- Facebook optimization -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta property="fb:app_id" content="132880950722117" />

    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:800|Roboto+Condensed" rel="stylesheet">
  </head>
  <body class='parallax'>
    <%= render 'shared/navbar', background: "transparent", shadow: "none" %>
    <%= yield %>
    <% unless current_page?(new_user_session_path) %>
      <%= render 'shared/footer' %>
    <% end %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>